// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQqxVTrmM_LEVtiE5_6uL1IHPU5k5kmYE',
    appId: '1:630133952828:web:0d330edfff6d1c08864e39',
    messagingSenderId: '630133952828',
    projectId: 'usermanual-app',
    authDomain: 'usermanual-app.firebaseapp.com',
    databaseURL:
        'https://usermanual-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'usermanual-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_neZSsqkDO0nYb1CpHw1xOH0ZulsM-gY',
    appId: '1:630133952828:android:e2359f5446e78479864e39',
    messagingSenderId: '630133952828',
    projectId: 'usermanual-app',
    databaseURL:
        'https://usermanual-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'usermanual-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALtc_JllW9KnY1Hbbrgo2WLraMc0OcVNI',
    appId: '1:630133952828:ios:d3c0023f4605ed58864e39',
    messagingSenderId: '630133952828',
    projectId: 'usermanual-app',
    databaseURL:
        'https://usermanual-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'usermanual-app.appspot.com',
    iosBundleId: 'com.example.userManualsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALtc_JllW9KnY1Hbbrgo2WLraMc0OcVNI',
    appId: '1:630133952828:ios:ed5599bb29139ef2864e39',
    messagingSenderId: '630133952828',
    projectId: 'usermanual-app',
    databaseURL:
        'https://usermanual-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'usermanual-app.appspot.com',
    iosBundleId: 'com.example.userManualsApp.RunnerTests',
  );
}
